#!/bin/bash

# don't forget to check 'source-code' in Software & Updates
# sudo add-apt-repository -y ppa:cassou/emacs

# sudo apt-get build-dep emacs24 -y

cd /tmp

wget http://ftpmirror.gnu.org/emacs/emacs-26.1.tar.xz
tar -xvf emacs-26.1.tar.xz

cd emacs-26.1
./configure
make
sudo make install

rm -rf /tmp/emacs-26.1
