#!/bin/bash

# don't forget to check 'source-code' in Software & Updates
sudo add-apt-repository -y ppa:cassou/emacs

sudo apt-get build-dep emacs24 -y

cd /tmp

wget http://alpha.gnu.org/gnu/emacs/pretest/emacs-24.4.91.tar.xz
tar -xvf emacs-24.4.91.tar.xz

cd emacs-24.4.91
./configure
make
sudo make install

rm -rf /tmp/emacs-24.4.91
