#!/usr/bin/env bash

set -euo pipefail

version=0.9.0

# Install the dependencies
sudo apt-get install -y openssl libcurl4-openssl-dev libxml2 libssl-dev libxml2-dev pinentry-curses xclip

# Get current version from repo
wget https://github.com/lastpass/lastpass-cli/archive/v$version.tar.gz
tar -xsvf v$version.tar.gz

cd lastpass-cli-$version

# Building
make
sudo make install

# Cleanup
cd ..
rm v$version.tar.gz
rm -rf lastpass-cli-$version