# espanso configuration file

# You can refer to the official documentation:
# https://espanso.org/docs/

matches:
  - trigger: ":numail"
    replace: "brunno.santos@nubank.com.br"

  # Dates
  - trigger: ":today"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  # Clipboard commands
  - trigger: ":mklink"
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"

  # Roamresearch texts
  - trigger: ":qa1"
    replace: "{{=:$|$ | }} #[[Leitner Box 1]]"
  - trigger: ":qa0"
    replace: "{{=:$|$ | }} #[[Leitner Box 0]]"
  - trigger: ":a2p"
    replace: "Added [[$|$]] to my #pocket, recommended by "
