# espanso configuration file

# You can refer to the official documentation:
# https://espanso.org/docs/

matches:
  - trigger: ":numail"
    replace: "brunno.santos@nubank.com.br"

  # Dates
  - trigger: ":today"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  # Clipboard commands
  - trigger: ":mklink"
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"
